export const MARKETPLACE_CATEGORIES = [
  {
    id: "airports",
    label: "Airports",
    slug: "airports",
    icon: "plane",
    description: "Security, check-in, bag drop, gate, rental, rideshare.",
    pricingModel: "moderate",
    workerTags: ["airport", "travel"],
  },
  {
    id: "concerts_festivals",
    label: "Concerts & Festivals",
    slug: "concerts-festivals",
    icon: "music",
    description: "GA entry lines, merch lines, and venue queues.",
    pricingModel: "premium",
    workerTags: ["events", "concerts"],
  },
  {
    id: "amusement_parks",
    label: "Amusement Parks",
    slug: "amusement-parks",
    icon: "ticket",
    description: "Attraction, gate-entry, and park services queues.",
    pricingModel: "moderate",
    workerTags: ["parks", "attractions"],
  },
  {
    id: "retail_drops",
    label: "Retail Drops / Product Launches",
    slug: "retail-drops",
    icon: "shopping-bag",
    description: "Sneaker drops, limited releases, and launch lines.",
    pricingModel: "surge",
    workerTags: ["retail", "drops"],
  },
  {
    id: "dmv_services",
    label: "DMV & Government Services",
    slug: "dmv-government-services",
    icon: "building",
    description: "DMV, passport, and local government office waits.",
    pricingModel: "flat-plus-time",
    workerTags: ["dmv", "government"],
  },
  {
    id: "restaurants",
    label: "Restaurants",
    slug: "restaurants",
    icon: "utensils",
    description: "Popular walk-in and waitlist queues.",
    pricingModel: "flex",
    workerTags: ["food", "dining"],
  },
  {
    id: "sporting_events",
    label: "Sporting Events",
    slug: "sporting-events",
    icon: "trophy",
    description: "Entry gates, team-store lines, and venue concessions.",
    pricingModel: "premium",
    workerTags: ["sports", "events"],
  },
  {
    id: "conventions_expos",
    label: "Conventions & Expos",
    slug: "conventions-expos",
    icon: "briefcase",
    description: "Badge pickup, featured session, and booth queues.",
    pricingModel: "moderate",
    workerTags: ["expo", "convention"],
  },
  {
    id: "tourist_attractions",
    label: "Tourist Attractions",
    slug: "tourist-attractions",
    icon: "camera",
    description: "Observation decks, museums, and attraction entry lines.",
    pricingModel: "moderate",
    workerTags: ["tourism", "attractions"],
  },
  {
    id: "popups_brand",
    label: "Pop-Ups / Brand Activations",
    slug: "popups-brand-activations",
    icon: "star",
    description: "Limited-time activations and pop-up experiences.",
    pricingModel: "surge",
    workerTags: ["popup", "brand"],
  },
  {
    id: "other",
    label: "Other / Custom Request",
    slug: "other-custom",
    icon: "sparkles",
    description: "Custom queue requests and niche waiting scenarios.",
    pricingModel: "custom",
    workerTags: ["custom"],
  },
] as const;

export type MarketplaceCategoryId = (typeof MARKETPLACE_CATEGORIES)[number]["id"];
