export type UserRole = "customer" | "waiter";

export type Profile = {
  id: string;
  role: UserRole;
  created_at: string;
  updated_at?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  last_initial?: string | null;
  display_name?: string | null;
  full_name?: string | null;
  avatar_url?: string | null;
  phone?: string | null;
  bio?: string | null;
  profile_completed?: boolean;
  stripe_account_id?: string | null;
  stripe_details_submitted?: boolean | null;
  stripe_payouts_enabled?: boolean | null;
  manual_payout_method?: string | null;
  serving_airports?: string[] | null;
  preferred_categories?: string[] | null;
  preferred_airport?: string | null;
  traveler_notes?: string | null;
  contact_preference?: string | null;
  home_airport?: string | null;
  airports_served?: string[] | null;
  is_available?: boolean;
  onboarding_completed?: boolean | null;
  onboarding_step?: number | null;
  onboarding_completed_at?: string | null;
  email_verified_at?: string | null;
  jobs_completed?: number;
  average_rating?: number | null;
  accepted_terms_version?: string | null;
  accepted_privacy_version?: string | null;
  accepted_refund_policy_version?: string | null;
  accepted_guidelines_version?: string | null;
  accepted_worker_agreement_version?: string | null;
  accepted_terms_at?: string | null;
  accepted_privacy_at?: string | null;
  accepted_refund_policy_at?: string | null;
  accepted_guidelines_at?: string | null;
  independent_contractor_acknowledged_at?: string | null;
  tax_responsibility_acknowledged_at?: string | null;
  /** Waiter progressive onboarding (DB trigger `update_waiter_gates`). */
  gate1_unlocked?: boolean | null;
  gate2_unlocked?: boolean | null;
  gate3_unlocked?: boolean | null;
  earnings_total?: number | null;
  jobs_completed_count?: number | null;
  jobs_accepted_count?: number | null;
};
